### ISSUE TITLE
HLS Sampler throws parsing error for MPEG-DASH file

### ISSUE THREAD

**Issue by c-raj** [Blazemeter/HLSPlugin#14]
We are currently using Blazemeter HLS sampler version 3.0.2 for our test. We are getting the following parsing error when testing with url - https://sri-amscdnep-ms.azureedge.net/cfdcffb9-e7bf-4068-b582-8400baf05b3a/BigBuckBunny.ism/manifest(format=mpd-time-csf)
`com.blazemeter.jmeter.videostreaming.core.exception.PlaylistParsingException: Error parsing contents from https://sri-amscdnep-ms.azureedge.net/cfdcffb9-e7bf-4068-b582-8400baf05b3a/BigBuckBunny.ism/manifest(format=mpd-time-csf)
	at com.blazemeter.jmeter.videostreaming.hls.Playlist.fromUriAndBody(Playlist.java:55) ~[jmeter-bzm-hls-3.0.2.jar:?]
	at com.blazemeter.jmeter.videostreaming.core.VideoStreamingSampler.downloadPlaylist(VideoStreamingSampler.java:120) ~[jmeter-bzm-hls-3.0.2.jar:?]
	at com.blazemeter.jmeter.videostreaming.hls.HlsSampler.downloadPlaylist(HlsSampler.java:97) ~[jmeter-bzm-hls-3.0.2.jar:?]
	at com.blazemeter.jmeter.videostreaming.hls.HlsSampler.downloadMasterPlaylist(HlsSampler.java:85) ~[jmeter-bzm-hls-3.0.2.jar:?]
	at com.blazemeter.jmeter.videostreaming.hls.HlsSampler.sample(HlsSampler.java:34) ~[jmeter-bzm-hls-3.0.2.jar:?]
	at com.blazemeter.jmeter.videostreaming.core.VideoStreamingSampler.sample(VideoStreamingSampler.java:79) [jmeter-bzm-hls-3.0.2.jar:?]
	at com.blazemeter.jmeter.hls.logic.HlsSampler.sample(HlsSampler.java:184) [jmeter-bzm-hls-3.0.2.jar:?]
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1271) [ApacheJMeter_http.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:627) [ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:551) [ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:490) [ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257) [ApacheJMeter_core.jar:5.2.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: com.blazemeter.jmeter.videostreaming.core.exception.PlaylistParsingException: Error parsing contents from https://sri-amscdnep-ms.azureedge.net/cfdcffb9-e7bf-4068-b582-8400baf05b3a/BigBuckBunny.ism/manifest(format=mpd-time-csf): No playlist tags found
	at com.blazemeter.jmeter.videostreaming.hls.Playlist.fromUriAndBody(Playlist.java:51) ~[jmeter-bzm-hls-3.0.2.jar:?]
	... 12 more`

Please help us fix this issue.

**Comment by RicardoPoleo** [comment]
Hello @c-raj, and thank you for reporting this. I wanted to let you know that we are checking both of the issues you reported (this and the [previous one](https://github.com/Blazemeter/HLSPlugin/issues/13)). I'll be back with you as soon as we fix it, or if more info is needed.

Cheers and see you soon!

**Comment by c-raj** [comment]
@RicardoPoleo Were you able to reproduce this issue?

**Comment by RicardoPoleo** [comment]
Hello @c-raj,

Thanks for keeping a tab on this. We fix this (among other issues) in our [last release,](https://github.com/Blazemeter/HLSPlugin/releases/) could you update it and try again?

Let me know if this solves your issue,

Kind regards

**Comment by RicardoPoleo** [comment]
Hello @c-raj ,

Any news regarding this issue? 

If not, I'm closing this thread and, if another issue appears, you are more than welcome to open another issue as well.

Hope to hear from you soon,

Kind regards
