### ISSUE TITLE
NullPointerException while parsing playlist

### ISSUE THREAD

**Issue by kontrollanten** [Blazemeter/HLSPlugin#18]
When I try to start a test the following error occurs. It seems like there's no URI to the video part. The playlist parsing seems to be done here https://github.com/Comcast/hlsparserj/blob/817454e4efe469e9b1b5656ad23b3d889345f1f5/src/main/java/com/comcast/viper/hlsparserj/MediaPlaylist.java#L166

But maybe the error is within the playlist file? The m3u8 file can be reached here https://we.tl/t-yDoUosysJl

```
2020-11-02 08:59:30,481 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'bzm - Streaming Sampler'.
java.lang.NullPointerException: null
	at java.net.URI$Parser.parse(URI.java:3104) ~[?:?]
	at java.net.URI.<init>(URI.java:600) ~[?:?]
	at java.net.URI.create(URI.java:881) ~[?:?]
	at com.blazemeter.jmeter.videostreaming.hls.Playlist.buildAbsoluteUri(Playlist.java:117) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at com.blazemeter.jmeter.videostreaming.hls.Playlist.lambda$getMediaSegments$1(Playlist.java:139) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.blazemeter.jmeter.videostreaming.hls.Playlist.getMediaSegments(Playlist.java:140) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at com.blazemeter.jmeter.videostreaming.hls.HlsSampler$MediaPlayback.updateMediaSegments(HlsSampler.java:116) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at com.blazemeter.jmeter.videostreaming.hls.HlsSampler$MediaPlayback.<init>(HlsSampler.java:110) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at com.blazemeter.jmeter.videostreaming.hls.HlsSampler$MediaPlayback.<init>(HlsSampler.java:100) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at com.blazemeter.jmeter.videostreaming.hls.HlsSampler.sample(HlsSampler.java:59) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at com.blazemeter.jmeter.videostreaming.core.VideoStreamingSampler.sample(VideoStreamingSampler.java:79) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at com.blazemeter.jmeter.hls.logic.HlsSampler.sample(HlsSampler.java:198) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1270) ~[ApacheJMeter_http.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:630) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.3]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

HLSPlugin version: 3.0.3
Jmeter version: 5.3

**Comment by RicardoPoleo** [comment]
Hello @kontrollanten,

For our delay, I'm sorry, we shouldn't leave you hanging. 

We experienced some issues regarding the protocol selection and other minor issues that, [in our last release](https://github.com/Blazemeter/HLSPlugin/releases/tag/v3.1), were fixed.

Could you please try it out and let us know if it works for you?

Hope to hear from you and, as always,

Happy Hacking!

**Comment by kontrollanten** [comment]
Thanks for your reply. I tried with the latest version and got the same result. Below is a screenshot of the settings.

![image](https://user-images.githubusercontent.com/6680299/116255108-3c04f400-a772-11eb-9acc-b5b2a77c30be.png)

**Comment by RicardoPoleo** [comment]
Thanks for your quick response @kontrollanten,

I'll check this with the team and let you know when we fix it.

That being said, I saw that this issue was mentioned on the [PeerTube's Community](https://github.com/Chocobozzz/PeerTube/issues/2625).  Do you know if their formatting was fixed? 

As always, thanks for taking the time,

**Comment by kontrollanten** [comment]
Thanks 👍🏻 I don't think that the formatting has been fixed/changed on PeerTube. I don't know what's wrong, so I can't propose a fix either.

**Comment by RicardoPoleo** [comment]
We reviewed the issue and, it looks like the problem is on our end, in the way we solve the byte ranges and obtain the URLs from them.

We will be working on fixing it and, when the release is done, we will let you know.

Anyways, thanks for taking the time @kontrollanten to test it and report it.

**Comment by kontrollanten** [comment]
Hi! Any updates on this?

**Comment by stevespaw** [comment]
We also have run into this issue. We are trying to get PeerTube videos playing on ROKU and Video.JS. Neither of these play with Audio. Try any PeerTube M3U8 here to replicate, this mirrors our Roku experience. This would really help us if it was fixed. [https://videojs-http-streaming.netlify.app/](https://videojs-http-streaming.netlify.app/)

**Comment by diego-ferrand** [comment]
Hey, we just launched a pre-release which should solve this issue. Please check it out and let us know what you think.

**Comment by RicardoPoleo** [comment]
Hello @kontrollanten,

Thanks for taking the time to report this behavior.

I did a test and this issue didn't appear. Did you update, by any chance, the `hlsparserj` library? We did some changes there as well. 

I would recommend you to do a smoke test using the libraries that were uploaded into the [pre-release v3.2](https://github.com/Blazemeter/HLSPlugin/releases/tag/v3.2), and let us know if this behavior remains.

Just for the record, I used those libraries with JMeter 5.5.

Once again, thanks for taking the time and happy hacking 🚀

**Comment by RicardoPoleo** [comment]
Yes, that seems to be working fine.

Upon clicking on "Load Playlist", all the variants for that playlist will be loaded into the UI, you just need to check the combo boxes to see them. For instance, I click on the Resolution and the following appears.
![Screen Shot 2022-09-30 at 11 46 17](https://user-images.githubusercontent.com/7467545/193295959-46187356-6bc7-4958-a965-519d47b74d17.png)

The same applies for bandwidth.
![Screen Shot 2022-09-30 at 11 46 01](https://user-images.githubusercontent.com/7467545/193295898-c7023898-8ac1-4f29-bcb4-c03846ec3a4b.png)

Apparently, there are no additional tracks for audio and subtitle.

Regarding the play button, you need to add a View Result Tree to your Test Plan in order to see it working (otherwise, the request will be made, but you won’t be able to see it, and that would be a shame, isn't it? 😉 ).
![Screen Shot 2022-09-30 at 11 48 54](https://user-images.githubusercontent.com/7467545/193296484-ef1215e3-1f24-4d1b-973c-c7f13da1fcbb.png)

I would recommend you to add the View Result Tree and see the results when playing the test plan. As long as there are no errors displayed in the log, we can discard the`NullPointerException` that we had prior to the pre-release.
![Screen Shot 2022-09-30 at 11 57 44](https://user-images.githubusercontent.com/7467545/193298327-17904574-67e6-4bec-a78d-db57db12efcf.png)


Just for good measure, I left each configuration by default, as shown below:
![Screen Shot 2022-09-30 at 11 55 04](https://user-images.githubusercontent.com/7467545/193297753-716363f5-78d3-4f4a-a358-29d0e96c414f.png)

Give it a try and let's see how it goes @kontrollanten
