### ISSUE TITLE
HLS passing parameters from Http managers

### ISSUE THREAD

**Issue by Crafter76** [Blazemeter/HLSPlugin#2]
HLS sample doesn't pass parameters from HTTP Cookie Manager, and HTTP Header Manager

java.io.IOException: Server returned HTTP response code: 401 for URL: https://dev-***.ru/videostream/camera1-90d2400146/tracks-v1a1/mono.m3u8
	at sun.reflect.GeneratedConstructorAccessor76.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1944) ~[?:1.8.0_201]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1939) ~[?:1.8.0_201]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_201]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1938) ~[?:1.8.0_201]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1508) ~[?:1.8.0_201]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_201]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_201]
	at com.blazemeter.jmeter.hls.logic.Parser.getBaseUrl(Parser.java:51) ~[jmeter-hls-1.3.jar:?]
	at com.blazemeter.jmeter.hls.logic.HlsSampler.getMasterList(HlsSampler.java:212) ~[jmeter-hls-1.3.jar:?]
	at com.blazemeter.jmeter.hls.logic.HlsSampler.sample(HlsSampler.java:141) [jmeter-hls-1.3.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:622) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:546) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:253) [ApacheJMeter_core.jar:5.0 r1840935]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]

**Comment by rabelenda** [comment]
Thank you for reporting this!

We are putting it on our backlog and will work on it.

Regards.

**Comment by rabelenda** [comment]
This should was fixed on release 2.0
