### ISSUE TITLE
Plugin not being able to parse valid HLS master playlist

### ISSUE THREAD

**Issue by kolevgeorgie** [Blazemeter/HLSPlugin#22]
- Issue: cannot parse properly the URI fomr url
- Tested with: `https://service.webvideocore.net/CL1olYogIrDWvwqiIKK7eBmnWbRkKKsu3nqabm9GlX02JOj3CDNXzodJMDEN2dk3/a_u6vp56x9vo08.m3u8`
- Stack trace:
```
2021-03-05 08:46:12,102 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'bzm - Streaming Sampler'.
java.lang.IllegalArgumentException: Illegal character in path at index 117: https://service.webvideocore.net/CL1olYogIrDWvwqiIKK7eBmnWbRkKKsu3nqabm9GlX02JOj3CDNXzodJMDEN2dk3/a_u6vp56x9vo08.m3u8 
	at java.net.URI.create(Unknown Source) ~[?:?]
	at com.blazemeter.jmeter.videostreaming.core.VideoStreamingSampler.sample(VideoStreamingSampler.java:78) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at com.blazemeter.jmeter.hls.logic.HlsSampler.sample(HlsSampler.java:198) ~[jmeter-bzm-hls-3.0.3.jar:?]
	at org.apache.jmeter.protocol.http.sampler.HTTPSamplerBase.sample(HTTPSamplerBase.java:1271) ~[ApacheJMeter_http.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:627) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:551) ~[ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:490) [ApacheJMeter_core.jar:5.2.1]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:257) [ApacheJMeter_core.jar:5.2.1]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.net.URISyntaxException: Illegal character in path at index 117: https://service.webvideocore.net/CL1olYogIrDWvwqiIKK7eBmnWbRkKKsu3nqabm9GlX02JOj3CDNXzodJMDEN2dk3/a_u6vp56x9vo08.m3u8 
	at java.net.URI$Parser.fail(Unknown Source) ~[?:?]
	at java.net.URI$Parser.checkChars(Unknown Source) ~[?:?]
	at java.net.URI$Parser.parseHierarchical(Unknown Source) ~[?:?]
	at java.net.URI$Parser.parse(Unknown Source) ~[?:?]
	at java.net.URI.<init>(Unknown Source) ~[?:?]
	... 9 more
```

**Comment by RicardoPoleo** [comment]
Hello @kolevgeorgie,

I'll be checking this issue with the team and get back to you when it is fixed or if we need some info from your end.

Thanks for taking the time and, as always,

Happy Hacking!

**Comment by diego-ferrand** [comment]
Hey @kolevgeorgie , we just launched a pre-release which should solve this issue. Please check it out and let us know what you think.
